#!/bin/bash
#
#head aega
#
echo -e "sisesta kella aeg"
read aeg
nimi=$( whoami )
if [ "$aeg" -ge 6 ] && [ "$aeg" -lt 12 ]
then echo "Tere Hommikust, $nimi!"
elif [ "$aeg" -ge 12 ] && [ "$aeg" -lt 18 ]
then echo "Tere Päevast, $nimi!"
elif [ "$aeg" -ge 18 ] && [ "$aeg" -lt 22 ]
then echo "Tere õhtust, $nimi!"
elif [ "$aeg" -ge 22 ] && [ "$aeg" -lt 25 ]
then echo "Head ööd, $nimi!"
elif [ "$aeg" -ge 0 ] && [ "$aeg" -lt 6 ]
then echo "Head ööd, $nimi!"
else echo "Vale sisend!"
fi #lõppetab if commandi
#lõpp
