#!/bin/bash
#
echo "Sisestage oma vanus: "
read vanus
if [ "$vanus" -ge 0 ] && [ "$vanus" -le 11 ]; then
echo "Sa oled laps"
elif [ "$vanus" -ge 12 ] && [ "$vanus" -le 18 ]; then
echo "Sa oled nooruk"
elif [ "$vanus" -ge 0 ] && [ "$vanus" -le 63 ]; then
echo "Sa oled täiskasvanu"
elif [ "$vanus" -ge 63 ]; then
echo "sa oled senjoor"
else
echo "Vigane sisend"
fi
#
#lõpp
