#!/bin/bash
#
#Pagari abi
#
echo "Sisestage kandiku pikkus ja laius (cm):" #küsib pikkusi
read pikkus ja laius #loeb vastust
echo "Sisestage kypsise pikkus ja laius (cm):" #küsib pikkusi
read kypsise_pikkus ja kypsise_laius #loeb vastust
echo "Sisestage kihtide arv" #küsi kihtide arvu
read kihtidearv #loeb vastust
echo "Sisestage küpsiste arv pakis" #küsib küpsiste arvu
read pakis #loeb vastust
aluskandik=`expr $pikkus \* $laius` #arvutab
kypsiseid=`expr $kypsise_pikkus \* $kypsise_laius` #arvutab
pakke=`expr $kihtidearv \* $pakis` #arvutab
pakkekokku=`expr $pakke \/ $pakis` #arvutab
echo "tuleb osta $pakkekokku pakki küpsiseid" #vastus
#
#Lõpp
