#!/bin/bash
#
#Inimeste loendur
#
echo -n "Inimeste arv: " #küsib inimeste arvu
read inimest #loeb vastust
echo -n "Mitu kohta on bussis:" #küsib kohti bussis
read kohta #loeb vastust
echo -n "Mitu bussi on :" #küsib mittu bussi on
read bussi #loeb vastust
koht=`expr $bussi \* $kohta` #tehted
echo=Bussis on $kohta tühja kohta #tehted
puudu=`expr $inimest - $koht` #tehted
echo "Maha jäi $puudu inimest" #vastus
#
#lõpp
