#!/bin/bash
#
#
echo "Sisestage mitu rida te soovite?"; read rida
echo "Sisestage tarnide arv reas?"; read tarnid
num=1
for (( i = 1; i <= $rida; i++ ))
do
echo -n "$num. "
let num++
for (( j = 1; j <= $tarnid; j++ ))
do
echo -n "* "
done
echo ""
done
